package:
  name: szip
  version: "2.1"

source:
  fn: szip-2.1.tar.gz
  url: http://www.hdfgroup.org/ftp/lib-external/szip/2.1/src/szip-2.1.tar.gz 
  sha1: d241c9acc26426a831765d660b683b853b83c131

build:
  number: 0

requirements:
  build:
   - gcc

test:
  commands:
    - exit $(test -f ${PREFIX}/lib/libsz.so) # [linux]
    - exit $(test -f ${PREFIX}/lib/libsz.dylib) # [osx]
