package:
  name: jasper
  version: "1.900.1"

source:
  fn:  jasper-1.900.1.zip
  url: http://www.ece.uvic.ca/~frodo/jasper/software/jasper-1.900.1.zip
  sha1: 9c5735f773922e580bf98c7c7dfda9bbed4c5191

build:
  number: 1
  detect_binary_files_with_prefix: true

requirements:
  build:
    - gcc

test:
  commands:
    - exit $(test -f ${PREFIX}/lib/libjasper.a)
